server:
  port: 9001
Spring:
  application:
    name: ywc-service-page
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ywc_lagou?Unicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123789
    